server:
  port: 8765
eureka:
  instance:
    hostname: eurekaserver2
    appname: eureka-cluster
  environment: local
  client:
    serviceUrl:
      defaultZone:
        http://eurekaserver1:8762/eureka
    register-with-eureka: true
    fetch-registry: true